### ISSUE TITLE
Excuse me, may I ask which article these code correspond to?

### ISSUE THREAD

**Issue by YuTongxuan** [simonetome/QuantumGeneticAlgorithm#1]
Excuse me, may I ask which article these code correspond to? I am also studying quantum genetic algorithm. I would really appreciate it if you could tell me which paper these code belong to, thank you very much!

**Comment by simonetome** [comment]
Hi @YuTongxuan, this was a MSc research project. I haven't submit the article to any journal, but I can upload it on the repo as soon as I can. In the written article there are some reference that you may find useful.

**Comment by simonetome** [comment]
@YuTongxuan you can find a project report draft with a bunch of useful references in the main folder under [report_draft.pdf](https://github.com/simonetome/QuantumGeneticAlgorithm/blob/main/report_draft.pdf).
